version: '3.8'

services:
  llama-core:
    build:
      context: ./packages/llama-core
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./packages/llama-core/models:/app/models
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sanara
      POSTGRES_PASSWORD: sanara123
      POSTGRES_DB: sanara
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sanara
      MONGO_INITDB_ROOT_PASSWORD: sanara123
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: sanara
      RABBITMQ_DEFAULT_PASS: sanara123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  mongodb_data:
  rabbitmq_data: