apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3NhbmFyYTpzYW5hcmExMjNAcG9zdGdyZXM6NTQzMi9zYW5hcmE=  # postgresql://sanara:sanara123@postgres:5432/sanara
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl  # your-jwt-secret-key-here 